### ISSUE TITLE
Addition of a an analytic function to the initial conditions code

### ISSUE THREAD

**Issue by jdha** [JMMP-Group/AMM7_zgr#8]
Addition of a (case 5) initialisation of temp and salinity with an analytic function dependent on depth only - this provides a sanity check against the spline interpolated T/S for the HPG testing

**Comment by anwiseNOCL** [comment]
A case 5 has been added to usrdef_istate.F90 where salinity and temperature are defined as simple exponential functions to represent the summer on-shelf T/S vertical profiles.
